name: FEST GUARD Runner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4

      - name: Node.js Kur
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Paketleri Yukle
        run: npm install

      - name: Botu Baslat
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: node index.js
